### PR TITLE
Update comment to include note about running migrations

### PR DESCRIPTION
**Pull request by eballerini**
Migrations must be applied manually, always.

Screen Shot 2020-05-20 at 9 07 55 AM

### CODE REVIEW

**Comment by mwarkentin** [comment]
Do we want to make that the bold piece of this message? Is that the mistake that people make most often with migrations? (I know it's the most recent but..)

**Comment by eballerini** [comment]
> Do we want to make that the bold piece of this message? Is that the mistake that people make most often with migrations? (I know it's the most recent but..)

@mwarkentin too much emphasis on that? I debated between the 2 and thought it was worth highlighting. Do you think it's better in normal font weight?

**Comment by mwarkentin** [comment]
@eballerini it doesn't look like we have a note about it in https://waveaccounting.atlassian.net/wiki/spaces/ENGG/pages/131596335/Database+Migrations

I would probably add a callout there, and highlight the migration playbook in the migbot message.

**Comment by mwarkentin** [comment]
I think these DB migration instructions are probably scary / complicated looking for people, so it would be nice if we also had some easy way for people to ping a group of experts for help.

**Comment by eballerini** [comment]
> I think these DB migration instructions are probably scary / complicated looking for people, so it would be nice if we also had some easy way for people to ping a group of experts for help.

Agreed but I think that would be part of another change.

**Comment by eballerini** [comment]
@mwarkentin I added a note in the playbook and change the font weight in the comment here.

**Pull request merged**
